# Generated by Django 5.0.6 on 2024-06-18 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderState',
            fields=[
                ('id_order_state', models.AutoField(primary_key=True, serialize=False)),
                ('order_state', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUser',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('date_order', models.DateField()),
                ('total_payment', models.FloatField()),
                ('address', models.CharField(max_length=80)),
                ('taxes', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=4000)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id_size', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80)),
                ('encrypted_password', models.CharField(max_length=80)),
                ('user_name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='UserRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('id_category',), name='category_id_category_un'),
        ),
        migrations.AddField(
            model_name='orderuser',
            name='order_state_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.orderstate'),
        ),
        migrations.AddField(
            model_name='image',
            name='productID_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.product'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.category'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.product'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='order_product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.orderuser'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='product_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.product'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='product_size_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.product'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='size_product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.size'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product_size_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.productsize'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_id_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.type'),
        ),
        migrations.AddField(
            model_name='orderuser',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.userinfo'),
        ),
        migrations.AddField(
            model_name='userrol',
            name='rol_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.rol'),
        ),
        migrations.AddField(
            model_name='userrol',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.userinfo'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('category_product_id', 'product_category_id'), name='productcategory_16_pk'),
        ),
        migrations.AddConstraint(
            model_name='productorder',
            constraint=models.UniqueConstraint(fields=('product_order_id', 'order_product_id'), name='productorder_pk'),
        ),
        migrations.AddConstraint(
            model_name='productsize',
            constraint=models.UniqueConstraint(fields=('product_size_id', 'size_product_id'), name='productsize_pk'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('product_size_id',), name='stock_unique'),
        ),
        migrations.AddConstraint(
            model_name='userrol',
            constraint=models.UniqueConstraint(fields=('user_id', 'rol_id'), name='usuario_rol_pk'),
        ),
    ]
